spring:
  application:
    name: business-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    password: postgres
    username: postgres
    database:
      host: localhost
      port: 5432
      name: sportline

  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
